### ISSUE TITLE
Render prop option

### ISSUE THREAD

**Issue by sami616** [alexvcasillas/cratebox-react#6]
Hi @alexvcasillas. Is there anyway to use the render prop pattern if you want to pass parts of your state to particular children?

eg

```
    <Consumer renderProp store={['state1', 'state2', 'state3']}>
      {({ state1, state2, state3 }) => (
        <>
          <ComponentOne {...state1} />
          <ComponentOne {...state2} />
          <ComponentOne {...state3} />
        </>
      )}
    </Consumer >

**Comment by alexvcasillas** [comment]
Hello @sami616 !!

Your example is correct, but just needs a little fix :)

```
    <Consumer store={['store_one', 'store_two', 'store_three']} direct>
      {({ cratebox, state: { store_one, store_two, store_three } }) => (
        <>
          <ComponentOne {...store_one} />
          <ComponentTwo {...store_two} />
          <ComponentThree {...store_three} />
        </>
      )}
    </Consumer >
```

You have to use the **direct** prop at the Consumer component, then, at the deconstruction of the function, you get two things: **cratebox** (where all the dispatch and stuff lives) and **state** (name is still to be defined and temporary) where the states of each store lives :)

And you'll have it working :)

I have to apologize because I still haven't documented this new way to use the Consumer component as a render prop pattern, but I have to say I'm working on it :)

I'm also curious and have to ask you: how will you use this render prop pattern? If it's like in the example, what benefit does this give to you? You have to be aware that if something on any of those three stores changes, it will re-render ComponentOne, ComponentTwo and ComponentThree, so I belive for the sake of the example (the one we're working with) it would be more useful the regular consumer

```
    <Consumer store="store_one">
          <ComponentOne />
   </Consumer>
    <Consumer store="store_two">
          <ComponentTwo />
   </Consumer>
    <Consumer store="store_three">
          <ComponentThree />
   </Consumer>
```

This way, you'll keep your subscriptions away from one store to each other and those stored states independent, this way, when you dispatch a change to, let's say, store_one, store_two and store_three consumers won't be affected and therefore, not re-rendered :)

Hope to hear back from you and thanks once again for using and testing this libraries :)

**Comment by sami616** [comment]
Hiya, yes totally - the use case for my particular example is pretty rare - good to know the lib supports render props as an option. nice work! :)
